name: Steven Guo
# Conversion
markdown:    kramdown

highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true

plugins:
  - jekyll-gist
  - jekyll-feed
  - jekyll-twitter-plugin